version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: hollar_webserver
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:    
      container_name: db_mysql_holla
      environment: 
          MYSQL_ROOT_PASSWORD: secret
      image: mysql:5.7
      restart: unless-stopped
      tty: true
      networks:
        - laravel
      ports:
          - 3308:3306/tcp
      volumes: 
          - ./src/data/mysql:/var/lib/mysql

  pma:
      container_name: hollapro_phpmyadmin
      environment: 
          MYSQL_DATABASE: holla_db
          MYSQL_ROOT_PASSWORD: secret
          PMA_HOST: db_mysql_holla
      image: phpmyadmin/phpmyadmin
      networks:
        - laravel
      ports:
          - 8888:80/tcp

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: holla
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: hollar_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: hollar_npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hollar_artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
